name: switchyomega
dependencies:
  browser: any
  crypto: any
  json: any
  polymer: any
  grinder: any
  yaml: any
  path: any
  unittest: any
transformers:
- polymer:
    entry_points:
    - web/options/options.html
    - web/background/background.html
    csp: true
